services:
  designly.api:
    image: designly.api
    build:
      context: .
      dockerfile: Designly.API/Dockerfile
    ports:
      - "5187:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  designly.client:
    image: designly.client
    build:
      context: .
      dockerfile: Designly.Client/Dockerfile
    ports:
      - "5288:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ApiBaseUrl=http://designly.api:8080
    depends_on:
      - designly.api
